#ifndef CONFIGURATION_HPP
#define CONFIGURATION_HPP

#ifndef CONFIG_WIFI_SSID
  #define CONFIG_WIFI_SSID "MY_SSID"
#endif
#ifndef CONFIG_WIFI_PASSWORD
  #define CONFIG_WIFI_PASSWORD "MY_PASSWORD"
#endif
#if !CONFIG_IP4_ADDRESS
  #define IP4_ADDRESS_U32 PP_HTONL(LWIP_MAKEU32(192,168,1,2))
#else
  #define IP4_ADDRESS_U32 PP_HTONL(LWIP_MAKEU32(CONFIG_IP4_ADDRESS_1,\
    CONFIG_IP4_ADDRESS_2,CONFIG_IP4_ADDRESS_3,CONFIG_IP4_ADDRESS_4))
#endif
#endif // CONFIGURATION_HPP
