#ifndef HTML_GPIO_CONFIG_HPP
#define HTML_GPIO_CONFIG_HPP

#if CONFIG_IP4_ADDRESS
  #define IP4_ADDRESS_U32 PP_HTONL(LWIP_MAKEU32(CONFIG_IP4_ADDRESS_1,\
    CONFIG_IP4_ADDRESS_2,CONFIG_IP4_ADDRESS_3,CONFIG_IP4_ADDRESS_4))
#endif

#endif // HTML_GPIO_CONFIG_HPP
